### ISSUE TITLE
Shotcut Project-File cannot be saved with recent Shotcut 22.10.25 

### ISSUE THREAD

**Issue by MaZderMind** [a-tze/fuse-ts#13]
I'm current working on getting fuse-ts compatible with the most recent Shotcut 22.10.25.
The fixes for supporting Tempfiles don't seem to be enough for 22.10.25.

I attached two SMB Captures which only contain the Save-Process. One ([fuse-ts-negative-original.pcapng.zip](https://github.com/a-tze/fuse-ts/files/9910372/fuse-ts-negative-original.pcapng.zip)) goes towards the current fuse-ts 2022.09.25.1 and exibits the failed writes to new and additional tempfiles.

The other one ([fuse-ts-positive.pcapng.zip](https://github.com/a-tze/fuse-ts/files/9910375/fuse-ts-positive.pcapng.zip)) goes towards a normal directory and shows, what a successful write looks like.

**Comment by MaZderMind** [comment]
Please note, that simply allowing `project_shotcut.mlt.XXXXXX` as additional Temp-File Pattern does not solvle the issue. That's what I already tried and Shotcut comes further along the Save-Process, but fails later with additional Temp-Files (see [fuse-ts-negative.pcapng.zip](https://github.com/a-tze/fuse-ts/files/9910390/fuse-ts-negative.pcapng.zip)) for a Trace of what that looks like.

**Comment by a-tze** [comment]
Yeah, I know.. that gave me some headache years ago already.
The point is, actually the fuse directory should advertise itself as being read-only, then Qt should fallback to "normal" behaviour:

https://github.com/mltframework/shotcut/blob/master/src/mltcontroller.cpp#L521

However, this could either interfere with KDEnlive, or be a solution for that saving procedure as well meaning that the whole tempfile stuff could be removed. So thats worth a try. I will create a branch shortly, and would be happy if xou could try that one.

**Comment by a-tze** [comment]
@MaZderMind Could you try https://github.com/a-tze/fuse-ts/tree/13-shotcut-project-file ?

**Comment by MaZderMind** [comment]
FTR I'm working here: https://github.com/a-tze/fuse-ts/compare/master...MaZderMind:fuse-ts:shotcut22
With that state, saving works again (though fuse-ts handling a write on the temp-file as a valid write) but Shotcut still reports an Error. I'm still looking into that.

Will try your idea/branch now.

**Comment by MaZderMind** [comment]
Hm with these changes, Shotcut will no even try to save at all:
```
Unable to write file project_shotcut.mlt
Perhaps you do not have permission.
Try again with a different folder.
```

This is not the change you intended, no?

**Comment by a-tze** [comment]
Oh no, shotcut checks the directory permission itself at an earlier stage... this makes setting the write fallback of QSaveFile to true pretty useless.

Ok, another approach, please check 88cae77 if you like.

**Comment by MaZderMind** [comment]
Yay! After adding support for the changed Shotcut22-Filenames and the new XML Format, that works:
https://github.com/a-tze/fuse-ts/compare/master...MaZderMind:13-shotcut-project-file

Let me clean up that code and open a PR 🎉
